### ISSUE TITLE
Test logs cannot be read properly

### ISSUE THREAD

**Issue by hugo187** [laposa/test-portal#81]
**Description**

I cannot properly analyse the logs of the tests. See the screenshots below how unpractical it is.

**Tasks**

- [ ] Add a horizontal scrollbar, so that I can see what's beyond the screen edge. Or introduce line wrapping. Right now, the `<pre>` element is offset from the left, but doesn't have a limit on the right causing it to overflow the screen.
- [ ] Decrease font size of the `<pre>` element. I would even go as low as 10px. Right now it's too large.
- [ ] Parse and render terminal escape sequences, so that I can see the formatting and colours instead of raw ANSI escape codes (such as ` [90m  │[39m [90mTests:[39m        [32m1[39m`). We could use [ansi_up.js](https://github.com/mariusstaicu/ansi-up) or [xterm.js](https://github.com/xtermjs/xterm.js).
- [ ] Try to remove timestamps from the logs. Please use regex `^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+(Z|[+-]\d{2}:\d{2})\s`, which should match a ISO timestamp at the start of a line. If at least one instance of timestamp is removed after this, then include a checkbox above the text with label "Show Timestamps". It should be unchecked by default.

**Screenshots**

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/032780d4-91ac-4a45-9adb-e369223084b1">

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/a88b1ed3-5885-473c-b40d-e063fb6c5293">
